export default {
    TEXT: "TEXT",

    ENUM: 'ENUM',

    DATETIME: 'DATETIME',

    VARIABLES: "VARIABLES",

    INLINE_SCRIPT: "INLINE_SCRIPT",

    ENVIRONMENT_VARIABLE: "ENVIRONMENT_VARIABLE",

    GLOBAL_VARIABLE: "GLOBAL_VARIABLE",

    // Reference

    PARAMETER_REFERENCE: "PARAMETER_REFERENCE",

    REQUEST_CHAIN: "REQUEST_CHAIN",

    // Encoding

    ENCODING_URL_ENCODE: 'ENCODING_URL_ENCODE',

    ENCODING_URL_DECODE: 'ENCODING_URL_DECODE',

    ENCODING_BASE64_ENCODE: 'ENCODING_BASE64_ENCODE',

    ENCODING_BASE64_DECODE: 'ENCODING_BASE64_DECODE',

    // Data

    FAKERJS: "FAKERJS",

    UUID: "UUID",

    JSON: "JSON",

    NONCE: "NONCE",

    INCREMENT_ID: "INCREMENT_ID",

    FILE_CONTENT: "FILE_CONTENT",

    // Crypto

    CRYPTO: "CRYPTO",

    ENCODING: "ENCODING"
}