import Vue
    from 'vue'

export const EvContentTabsEventBus = new Vue()

export const EvContentTabsEvents = {
    SELECT_CONTENT_TAB: "SELECT_CONTENT_TAB",

    CLOSE_CONTENT_TAB: "CLOSE_CONTENT_TAB",

    CLOSE_CONTENT_TABS: "CLOSE_CONTENT_TABS",

    PIN_CONTENT_TAB: "PIN_CONTENT_TAB",

    CLOSE_OTHER_CONTENT_TABS: "CLOSE_OTHER_CONTENT_TABS",

    CLOSE_TABS_TO_THE_LEFT: "CLOSE_TABS_TO_THE_LEFT",

    CLOSE_TABS_TO_THE_RIGHT: "CLOSE_TABS_TO_THE_RIGHT",

    CLOSE_ALL_CONTENT_TABS: "CLOSE_ALL_CONTENT_TABS",

    BACK_TO_TOP: "BACK_TO_TOP",

    SWITCH_TO_API_DEFINITION: "SWITCH_TO_API_DEFINITION",

    SWITCH_TO_HTTP_OPERATION: "SWITCH_TO_HTTP_OPERATION",

    SWITCH_TO_MOCK_OPERATION: "SWITCH_TO_MOCK_OPERATION",

    // Emit By JsonTreeView

    NAVIGATE_TO_API_DEFINITION: "NAVIGATE_TO_API_DEFINITION",

    NAVIGATE_TO_STRUCT_DEFINITION: "NAVIGATE_TO_STRUCT_DEFINITION",

    NAVIGATE_TO_HTTP_CLIENT: "NAVIGATE_TO_HTTP_CLIENT",

    NAVIGATE_TO_MOCK_CLIENT: "NAVIGATE_TO_MOCK_CLIENT",

    // Emit By ApiTreeView

    NAVIGATE_TO_HTTP_REQUEST: "NAVIGATE_TO_HTTP_REQUEST",

    CLOSE_CONTENT_TAB_BY_HTTP_REQUEST: "CLOSE_CONTENT_TAB_BY_HTTP_REQUEST",

    NAVIGATE_TO_HTTP_DEFINITION: "NAVIGATE_TO_HTTP_DEFINITION",

    CLOSE_CONTENT_TAB_BY_HTTP_DEFINITION: "CLOSE_CONTENT_TAB_BY_HTTP_REQUEST",

    // NAVIGATE_TO_HTTP_OPERATION: "NAVIGATE_TO_HTTP_OPERATION",
}