const GHCContentTabType = {
    /**
     * @deprecated
     */
    WELCOME: "WELCOME",

    OVERVIEW: "OVERVIEW",

    // Old

    API_DEFINITION: "API_DEFINITION",

    STRUCT_DEFINITION: "STRUCT_DEFINITION",

    API_HTTP_CLIENT: "API_HTTP_CLIENT",

    API_MOCK_CLIENT: "API_MOCK_CLIENT",

    API_HTTP_REQUEST: "API_HTTP_REQUEST",

    // New

    HTTP_OPERATION: "HTTP_OPERATION",

    MOCK_OPERATION: "MOCK_OPERATION",

    HTTP_DEFINITION: "HTTP_DEFINITION",

    WEBSOCKET_OPERATION: "WEBSOCKET_OPERATION"
}

export default GHCContentTabType