<template>
    <div class="ev-http-client-code-snippets-sidebar">
        <!--        <div class="snippets-intro">-->
        <!--            <ev-label size="10" grey>点击选择框后在导出菜单中启用该项</ev-label>-->
        <!--        </div>-->

        <div class="d-flex flex-column" v-for="target in snippets">
            <div class="snippets-target">
                <ev-label size="12" secondary bold>{{ target.name }}</ev-label>

                <div class="snippets-target__divider"></div>
            </div>

            <div class="snippets-client" :class="{'snippets-client--selected': client === selectedClient}" v-for="client in target.clients" @click="doSelectClient(target, client)">
                <!--                <ev-export-check-box v-model="client.checkedStatus"></ev-export-check-box>-->

                <ev-vertical-gutter :gutter="4"></ev-vertical-gutter>

                <ev-label size="12" primary>{{ client.name }}</ev-label>
            </div>
        </div>

        <div class="snippets-intro">
            <ev-label size="10" grey>{{ $t('sponsor') }}</ev-label>
        </div>
    </div>
</template>

<script>
    import EvLabel from '@/components/typography/EvLabel'
    import EvExportCheckBox from '@/modals/export-project/export-filter/EvExportCheckBox'
    import EvVerticalGutter from '@/components/layout/EvVerticalGutter'

    export default {
        name: "EvHttpClientCodeSnippetsSidebar",

        components: {
            EvVerticalGutter,
            EvExportCheckBox,
            EvLabel
        },

        props: {
            snippets: Array,

            selectedClient: Object
        },

        data() {
            return {}
        },

        methods: {
            doSelectClient(target, client) {
                this.$emit('select-client', target, client)
            },
        },

        i18n: {
            messages: {
                en: {
                    sponsor: "* Code Snippets generated by httpsnippet"
                },
                zh: {
                    sponsor: "* 本功能由 httpsnippet 提供"
                }
            }
        }
    }
</script>

<style lang="scss" scoped>
    @import "~@/styles/rabiapi.scss";

    @import "~@/styles/scrollbar.scss";

    .ev-http-client-code-snippets-sidebar {
        display: flex;

        flex-direction: column;

        min-height: 0px;

        min-width: 0px;

        width: 240px;

        height: 600px;

        background-color: #F5F5F5;

        border-right: 1px solid #e0e0e0;

        overflow-y: scroll;

        .snippets-intro {
            display: flex;

            //flex-direction: column;

            align-items: center;

            //justify-content: center;

            flex-shrink: 0;

            height: 32px;

            width: 100%;

            padding-left: 8px;

            //background-color: #FF8282;
        }

        .snippets-target {
            display: flex;

            align-items: center;

            width: 100%;

            height: 28px;

            padding-left: 8px;

            //background-color: #FF8282;

            &__divider {
                display: flex;

                //width: 100%;
                flex: 1;

                height: 1px;

                margin-left: 8px;

                margin-right: 8px;

                border-bottom: 1px solid #E0E0E0;
            }
        }

        .snippets-client {
            display: flex;

            align-items: center;

            padding-left: 8px;

            height: 24px;

            &--selected {
                background-color: #E0E0E0;
            }
        }
    }
</style>
