import Vue
    from 'vue'

export const EvJsonTreeViewEventBus = new Vue()

export const EvJsonTreeViewEvents = {
    // Search

    SEARCH: "SEARCH",

    NO_SEARCH_RESULTS: "NO_SEARCH_RESULTS",

    SEARCH_JSON_SERVICE_MATCHED: "JSON_SERVICE_MATCHED",

    SEARCH_JSON_METHOD_MATCHED: "JSON_METHOD_MATCHED",

    AIM: "AIM",

    EXPAND_ALL: "EXPAND_ALL",

    COLLAPSE_ALL: "COLLAPSE_ALL",

    EXPAND_SERVICE: "EXPAND_SERVICE", // Expand target jsonService, if not, collapse

    COLLAPSE_SERVICE: "COLLAPSE_SERVICE",

    // Select

    // Public Events

    SELECT_JSON_METHOD: "SELECT_JSON_METHOD",

    // Private Events

    _SELECT_JSON_METHOD: "_SELECT_JSON_METHOD",

    _SELECT_HTTP_OPERATION: "_SELECT_HTTP_OPERATION",

    _DELETE_HTTP_OPERATION: "_DELETE_HTTP_OPERATION",

    _DUPLICATE_HTTP_OPERATION: "_DUPLICATE_HTTP_OPERATION",

    _SELECT_MOCK_OPERATION: "_SELECT_MOCK_OPERATION",

    _DELETE_MOCK_OPERATION: "_DELETE_MOCK_OPERATION",

    _DUPLICATE_MOCK_OPERATION: "_DUPLICATE_MOCK_OPERATION",

    _SHOW_CONTEXT_MENU: "_SHOW_CONTEXT_MENU",

    // Http Operation Events | PUBLIC | EvContentTab

    SELECT_HTTP_OPERATION: "SELECT_HTTP_OPERATION",

    CREATE_HTTP_OPERATION: "CREATE_HTTP_OPERATION",

    DUPLICATE_HTTP_OPERATION: "DUPLICATE_HTTP_OPERATION",

    DELETE_HTTP_OPERATION: "DELETE_HTTP_OPERATION",

    // Mock Operation Events | PUBLIC | EvContentTab

    SELECT_MOCK_OPERATION: "SELECT_MOCK_OPERATION",

    CREATE_MOCK_OPERATION: "CREATE_MOCK_OPERATION",

    DUPLICATE_MOCK_OPERATION: "DUPLICATE_MOCK_OPERATION",

    DELETE_MOCK_OPERATION: "DELETE_MOCK_OPERATION"
}