import KeyValueRelationship
    from '@/views/http-client/request/key-value-editor/KeyValueRelationship'
import GHCComponent
    from '@/data/gotcha/GHCComponent'
import KeyValueItemSource
    from '@/views/http-client/request/key-value-editor/KeyValueItemSource'

class KeyValueItem extends GHCComponent {
    constructor(key, value) {
        super()

        this.key = key || ""

        /**
         * @type {string}
         * @since 1.4.6
         */
        this.type = 'text' // text | array

        this.value = value || "" // Plain Text / Dynamic Variable

        this.description = ""

        this.keyPlaceholder = "Key"

        this.valuePlaceholder = "Value"

        /**
         * Relationship between key and value
         *
         * @type {string}
         */
        this.relationship = KeyValueRelationship.EQUALS

        /**
         * Generated by system or custom
         *
         * @type {string}
         */
        this.source = KeyValueItemSource.TEMPLATE

        this.checkedStatus = "CHECKED"

        /**
         * @type {string}
         * @since 1.4.1
         */
        this.requiredStatus = "CHECKED"

        this.isDeletable = true

        /**
         * Cannot edit key
         *
         * @type {boolean}
         */
        this.isEditable = true

        this.isSortable = true

        this.isRequired = false

        this.constraint = undefined

        /**
         * @type {*[]}
         * @since 1.4.8
         */
        this.children = []
    }

    /**
     * @param {JsonStruct} jsonStruct
     */
    static buildFromJsonStruct(jsonStruct) {
        let item = new KeyValueItem()

        item.key = jsonStruct.fieldName

        item.value = ""

        item.keyPlaceholder = ""

        item.valuePlaceholder = jsonStruct.summary

        item.isDeletable = false

        item.isEditable = false

        item.isRequired = jsonStruct.isRequired

        item.constraint = jsonStruct.constraint

        return item
    }
}

export default KeyValueItem