import Vue
    from 'vue'

export const AppEventBus = new Vue()

export const AppEvents = {
    INITIALIZE_PROJECTS: "INITIALIZE_PROJECTS",

    INITIALIZE_PROJECTS_FINISHED: "INITIALIZE_PROJECTS_FINISHED",

    IMPORT_PROJECT: "IMPORT_PROJECT",

    IMPORT_PROJECT_FINISHED: "IMPORT_PROJECT_FINISHED",

    IMPORT_PROJECT_FAILED: "IMPORT_PROJECT_FAILED",

    CREATE_PROJECT: "CREATE_PROJECT",

    CREATE_PROJECT_FINISHED: "CREATE_PROJECT_FINISHED",

    TRY_REMOVE_PROJECT: "TRY_REMOVE_PROJECT",

    REMOVE_PROJECT: "REMOVE_PROJECT",

    REMOVE_PROJECT_FINISHED: "REMOVE_PROJECT_FINISHED",

    REMOVE_VERSION: "REMOVE_VERSION",

    REMOVE_VERSION_FINISHED: "REMOVE_VERSION_FINISHED",

    SELECT_PROJECT: "SELECT_PROJECT",

    SELECT_VERSION: "SELECT_VERSION",

    SELECT_MODULE: "SELECT_MODULE",

    SELECT_TREE_VIEW_GROUP: "SELECT_TREE_VIEW_GROUP",

    // Settings

    CHANGE_LOCALE: "CHANGE_LOCALE",

    // UI Control

    SHOW_CONTEXT_MENU: "SHOW_CONTEXT_MENU",

    TOGGLE_APP_SIDEBAR: "TOGGLE_APP_SIDEBAR"
}
